In [2]:
#new project hehe

In [3]:
import opendatasets as od
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
dataset = 'https://www.kaggle.com/datasets/siddharthm1698/coursera-course-dataset'

In [5]:
def data_from_kaggle(dataset):
    """
    Download a Kaggle dataset using opendatasets and return the loaded DataFrame. Works with only one csv
    
    Args:
        dataset: Kaggle dataset URL.
    
    Returns:
        df (pd.DataFrame): CSV file found in the dataset folder, converted to pd.DataFrame
    """
    data_dir =  od.download(dataset)
    if data_dir is None:
        # Extract folder name from URL
        folder_name = dataset.split('/')[-1]
        data_dir = f'./{folder_name}'
    file = os.listdir(data_dir)
    csv_path = os.path.join(data_dir, file[0])
    df = pd.read_csv(csv_path)
    return df

In [6]:
cours = data_from_kaggle(dataset) #you'll need your Kaggle credentials (username and API key) to use that

Skipping, found downloaded files in ".\coursera-course-dataset" (use force=True to force download)

In [7]:
cours.head()

,Unnamed: 0,course_title,course_organization,course_Certificate_type,course_rating,course_difficulty,course_students_enrolled
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5.3k
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17k
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130k
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91k
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320k

In [8]:
cours.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                891 non-null    int64
 1   course_title              891 non-null    object
 2   course_organization       891 non-null    object
 3   course_Certificate_type   891 non-null    object
 4   course_rating             891 non-null    float64
 5   course_difficulty         891 non-null    object
 6   course_students_enrolled  891 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 48.9+ KB

In [9]:
#CLEANING

In [10]:
#drop unnamed column, students enrolled to int in thousands, course diffuculty maybe

In [15]:
cours_cleaned = cours.drop(columns = ["Unnamed: 0"])

In [16]:
cours_cleaned.head()

,course_title,course_organization,course_Certificate_type,course_rating,course_difficulty,course_students_enrolled
0,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5.3k
1,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17k
2,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130k
3,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91k
4,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320k

In [17]:
cours_cleaned = cours_cleaned.drop_duplicates()

In [19]:
cours_cleaned.shape

(891, 6)

In [20]:
cours.shape

(891, 7)

In [ ]:
#no duplicates

In [ ]:
#looking at nan values

In [22]:
cours_cleaned.isnull().sum()

course_title                0
course_organization         0
course_Certificate_type     0
course_rating               0
course_difficulty           0
course_students_enrolled    0
dtype: int64

In [23]:
cours_cleaned = cours_cleaned.rename( columns = {
    'course_title':'Title',
    'course_organization': 'Organization',
    'course_Certificate_type': 'Certificate', 
    'course_rating' : 'Rating', 
    'course_difficulty' : 'Difficulty', 
    'course_students_enrolled': 'Students(thousands)' 
}
                                    )

In [24]:
cours_cleaned.head()

,Title,Organization,Certificate,Rating,Difficulty,Students(thousands)
0,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5.3k
1,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17k
2,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130k
3,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91k
4,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320k

In [25]:
cours_cleaned['Students(thousands)'] = cours_cleaned['Students(thousands)'].str.replace('k', '').str.strip()

In [27]:
cours_cleaned['Students(thousands)'].unique()

array(['5.3', '17', '130', '91', '320', '39', '350', '2.4', '61', '12',
       '4', '13', '11', '27', '110', '6.6', '540', '22', '2.9', '80',
       '9.9', '23', '9.2', '78', '190', '35', '29', '14', '21', '94',
       '69', '40', '220', '150', '18', '270', '7.9', '30', '36', '20',
       '8.1', '120', '71', '63', '42', '480', '97', '200', '180', '4.2',
       '310', '3.9', '79', '31', '15', '10', '66', '33', '56', '7.3',
       '9.7', '210', '28', '6.5', '55', '2.3', '8.8', '88', '1.9', '68',
       '1.6', '9.5', '57', '26', '84', '95', '5.8', '24', '67', '280',
       '38', '77', '510', '89', '48', '160', '32', '340', '82', '790',
       '19', '51', '4.8', '37', '43', '6.4', '49', '240', '46', '7.8',
       '75', '81', '140', '5.5', '99', '100', '3', '830', '740', '60',
       '96', '690', '44', '4.5', '8.2', '16', '300', '8', '41', '54', '9',
       '380', '58', '5.6', '7.1', '83', '3.4', '1.5', '230', '760', '86',
       '45', '7.2', '1.8', '4.1', '76', '490', '170', '260', '65', '470',
       '400', '4.4', '62', '64', '3.2', '52', '290', '25', '47', '4.9',
       '9.4', '34', '59', '73', '3.6', '7.6', '3.8', '93', '430', '7.4',
       '5.4', '1.7', '98', '3.5', '3.3', '2.2', '610', '72', '85', '8.7',
       '53', '2.6', '390', '74', '6', '87', '370', '6.3', '5.9', '3.2m',
       '8.4', '9.1', '70', '630', '250', '330', '6.2', '92', '8.9', '50',
       '1.3m', '440', '420', '1.5m', '7.7', '5.2', '7', '6.8', '750',
       '8.5', '90', '2.5m', '6.1', '9.8'], dtype=object)

In [ ]:
#we can also see that there are some millions as well, so we have to change that to thousands and then delete m
#One million is 1000 thousands, so we

In [30]:
cours_cleaned[cours_cleaned['Students(thousands)'].str.contains('m', case=False)]

,Title,Organization,Certificate,Rating,Difficulty,Students(thousands)
564,Machine Learning,Stanford University,COURSE,4.9,Mixed,3.2m
674,Programming for Everybody (Getting Started wit...,University of Michigan,COURSE,4.8,Mixed,1.3m
688,Python for Everybody,University of Michigan,SPECIALIZATION,4.8,Beginner,1.5m
815,The Science of Well-Being,Yale University,COURSE,4.9,Mixed,2.5m

In [ ]:
#there are only 4 courses and each of them has a decimal value, so since each million contains 1000 thousands, and since, for
#example 3.2m = 3200 thousands, what we'll do is just replace m with 00 and delete a period

In [35]:
def m_to_k(x):
    x = str(x)

    if x.endswith('m'):              
        return float(x[:-1]) * 1000 
    else:
        return float(x)

In [36]:
cours_cleaned['Students(thousands)'] = cours_cleaned['Students(thousands)'].apply(m_to_k)

In [42]:
np.set_printoptions(suppress=True) #suppressing scientific notation

In [43]:
#sanity check let's see if only right values were affected
cours_cleaned['Students(thousands)'] .unique()

array([   5.3,   17. ,  130. ,   91. ,  320. ,   39. ,  350. ,    2.4,
         61. ,   12. ,    4. ,   13. ,   11. ,   27. ,  110. ,    6.6,
        540. ,   22. ,    2.9,   80. ,    9.9,   23. ,    9.2,   78. ,
        190. ,   35. ,   29. ,   14. ,   21. ,   94. ,   69. ,   40. ,
        220. ,  150. ,   18. ,  270. ,    7.9,   30. ,   36. ,   20. ,
          8.1,  120. ,   71. ,   63. ,   42. ,  480. ,   97. ,  200. ,
        180. ,    4.2,  310. ,    3.9,   79. ,   31. ,   15. ,   10. ,
         66. ,   33. ,   56. ,    7.3,    9.7,  210. ,   28. ,    6.5,
         55. ,    2.3,    8.8,   88. ,    1.9,   68. ,    1.6,    9.5,
         57. ,   26. ,   84. ,   95. ,    5.8,   24. ,   67. ,  280. ,
         38. ,   77. ,  510. ,   89. ,   48. ,  160. ,   32. ,  340. ,
         82. ,  790. ,   19. ,   51. ,    4.8,   37. ,   43. ,    6.4,
         49. ,  240. ,   46. ,    7.8,   75. ,   81. ,  140. ,    5.5,
         99. ,  100. ,    3. ,  830. ,  740. ,   60. ,   96. ,  690. ,
         44. ,    4.5,    8.2,   16. ,  300. ,    8. ,   41. ,   54. ,
          9. ,  380. ,   58. ,    5.6,    7.1,   83. ,    3.4,    1.5,
        230. ,  760. ,   86. ,   45. ,    7.2,    1.8,    4.1,   76. ,
        490. ,  170. ,  260. ,   65. ,  470. ,  400. ,    4.4,   62. ,
         64. ,    3.2,   52. ,  290. ,   25. ,   47. ,    4.9,    9.4,
         34. ,   59. ,   73. ,    3.6,    7.6,    3.8,   93. ,  430. ,
          7.4,    5.4,    1.7,   98. ,    3.5,    3.3,    2.2,  610. ,
         72. ,   85. ,    8.7,   53. ,    2.6,  390. ,   74. ,    6. ,
         87. ,  370. ,    6.3,    5.9, 3200. ,    8.4,    9.1,   70. ,
        630. ,  250. ,  330. ,    6.2,   92. ,    8.9,   50. , 1300. ,
        440. ,  420. , 1500. ,    7.7,    5.2,    7. ,    6.8,  750. ,
          8.5,   90. , 2500. ,    6.1,    9.8])

In [47]:
cours_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                891 non-null    object
 1   Organization         891 non-null    object
 2   Certificate          891 non-null    object
 3   Rating               891 non-null    float64
 4   Difficulty           891 non-null    object
 5   Students(thousands)  891 non-null    float64
dtypes: float64(2), object(4)
memory usage: 48.7+ KB

In [48]:
#finished with data prepping(still not clean, just works) let's answer some questionsss

In [ ]:
#ANSWERING QUESTIONS IN DATASET

In [ ]:
#how many types of certificates, how many organizations, possibly correlation between difficulty and nb of students

In [49]:
df = cours_cleaned.copy()

In [ ]:
#how many courses in dataset

In [52]:
print(f"There are {len(df)} courses in this dataset")

There are 891 courses in this dataset

In [ ]:
#What are different certification types present in the dataset

In [53]:
res = ', '.join(df['Certificate'].unique())

In [59]:
print(f"There are {len(df['Certificate'].unique())} certification types.\nHere is a list of all of them: {res.lower()}")

There are 3 certification types.
Here is a list of all of them: specialization, course, professional certificate

In [ ]:
#how many courses per certification type

3